'use strict';
const API='https://jgjvzqfxakvogaeqfual.supabase.co/functions/v1/client-tracker', $=id=>document.getElementById(id), labels={activo:'Activo',muerto:'Inactivo / Muerto',seguimiento:'Para seguimiento'};
const drafts=new Map();
let saving=false;
let key='',role='',clients=[],sellers=[],selected=new Set(),sellerFilter=new Set(),statusFilter=new Set(),limit=60,book=null,rows=[],previewRows=null;
const money=n=>new Intl.NumberFormat('es-AR',{maximumFractionDigits:2}).format(n),date=s=>s?s.split('-').reverse().join('/'):'Sin fecha';
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function message(t,error=false){$('message').textContent=t;$('message').className=error?'error':'success';}
async function api(action,body={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-tracker-key':key},body:JSON.stringify({action,...body})});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar la operación');return d;}
async function guard(fn,button){if(button)button.disabled=true;try{await fn()}catch(e){message(e.message,true)}finally{if(button)button.disabled=false}}
function updateSaveBar(){
 const count=drafts.size;
 $('saveBar').hidden=!count&&!saving;
 document.body.classList.toggle('has-pending',count>0||saving);
 $('saveAll').disabled=saving||!count;
 $('saveAll').textContent=saving?'Guardando…':'Guardar cambios';
 $('saveStatus').textContent=saving?'No cierres esta página.':count+' cliente'+(count===1?'':'s')+' con cambios pendientes';
 $('refresh').disabled=saving;
 $('logout').disabled=saving;
}
async function saveAllChanges(){
 if(saving||!drafts.size)return;
 saving=true;
 const batch=[...drafts.entries()].map(([id,d])=>[id,{...d}]);
 render();
 let saved=0;const failed=[];
 try{
  for(const [id,draft] of batch){
   try{
    const updated=await api('mark',{id,...draft});
    const client=clients.find(c=>c.id===id);
    if(client)Object.assign(client,updated);
    drafts.delete(id);saved++;
   }catch(e){failed.push((clients.find(c=>c.id===id)?.name||'Cliente')+': '+e.message);}
  }
 }finally{
  saving=false;render();
  if(role==='admin')renderSellers();
 }
 message(failed.length?saved+' guardados. '+failed.length+' pendientes; no se perdieron los cambios. '+failed.join(' · '):'Cambios guardados online: '+saved+' cliente'+(saved===1?'':'s')+'.',failed.length>0);
}
$('saveAll').onclick=saveAllChanges;
function sellerName(id){return sellers.find(s=>s.id===id)?.name||'Vendedor';}
async function load(){const d=await api('load');role=d.role;clients=d.clients;sellers=d.sellers;selected=new Set([...selected].filter(id=>clients.some(c=>c.id===id)));$('login').hidden=true;$('app').hidden=false;$('admin').hidden=role!=='admin';$('sellerFilters').hidden=role!=='admin';$('duplicatesLabel').hidden=role!=='admin';$('title').textContent=role==='admin'?'Panel de administrador':sellers[0]?.name||'Mi cartera';$('subtitle').textContent=role==='admin'?'Importá, compartí y seguí los avances de tu equipo.':'Actualizá el estado y las notas de tus clientes.';$('synced').textContent='Actualizado '+new Date().toLocaleTimeString('es-AR');if(role==='admin')renderSellers();renderFilters();render();}
function check(label,value,set,container){const l=el('label','check');const i=el('input');i.type='checkbox';i.checked=set.has(value);i.onchange=()=>{i.checked?set.add(value):set.delete(value);limit=60;render()};l.append(i,document.createTextNode(label));container.append(l);}
function renderFilters(){const sf=$('sellerFilters');sf.replaceChildren();for(const s of sellers)check(s.name,s.id,sellerFilter,sf);const st=$('statusFilters');st.replaceChildren();for(const [k,l]of Object.entries(labels))check(l,k,statusFilter,st);}
function duplicates(){const m=new Map();for(const c of clients){if(!m.has(c.identity))m.set(c.identity,new Set());m.get(c.identity).add(c.seller_id)}return m;}
function filtered(){const q=TrackerCore.norm($('search').value),dups=duplicates(),from=$('from').value,to=$('to').value;return clients.filter(c=>(!sellerFilter.size||sellerFilter.has(c.seller_id))&&(!statusFilter.size||statusFilter.has(c.status))&&TrackerCore.norm(c.name).includes(q)&&(!from||(c.last_sale&&c.last_sale>=from))&&(!to||(c.last_sale&&c.last_sale<=to))&&(!$('duplicates').checked||dups.get(c.identity).size>1)).sort((a,b)=>$('sort').value==='name'?a.name.localeCompare(b.name):$('sort').value==='last'?(b.last_sale||'').localeCompare(a.last_sale||''):b.paid-a.paid);}
function render(){const list=filtered(),dup=duplicates();$('totalClients').textContent=list.length;$('paid').textContent='$ '+money(list.reduce((s,c)=>s+Number(c.paid),0));$('pending').textContent='$ '+money(list.reduce((s,c)=>s+Number(c.pending),0));$('count').textContent=list.length+' de '+clients.length+' fichas · '+list.filter(c=>selected.has(c.id)).length+' marcadas en esta vista';const grid=$('grid');grid.replaceChildren();if(!list.length)grid.append(el('p','','No hay clientes para estos filtros.'));for(const c of list.slice(0,limit)){const draft=drafts.get(c.id);const card=el('article','card'),top=el('div','foot'),sel=el('input');sel.type='checkbox';sel.checked=selected.has(c.id);sel.setAttribute('aria-label','Seleccionar '+c.name);sel.onchange=()=>{sel.checked?selected.add(c.id):selected.delete(c.id);$('count').textContent=list.length+' de '+clients.length+' fichas · '+list.filter(c=>selected.has(c.id)).length+' marcadas en esta vista'};top.append(el('span','tag',sellerName(c.seller_id)),sel);card.append(top,el('h2','',c.name),el('span','label',c.network+' · Total pagado USD'),el('div','amount','$ '+money(c.paid)),el('p','pending','Pendiente: USD '+money(c.pending)));if(role==='admin'&&dup.get(c.identity).size>1)card.append(el('p','shared','También en: '+[...dup.get(c.identity)].filter(id=>id!==c.seller_id).map(sellerName).join(', ')));const dates=el('div','dates');for(const [l,v]of [['Primera venta',c.first_sale],['Última venta',c.last_sale]]){const d=el('div');d.append(el('span','label',l),el('strong','',date(v)));dates.append(d)}card.append(dates);const state=el('select','state '+c.status);state.setAttribute('aria-label','Estado de '+c.name);for(const [v,l]of Object.entries(labels)){const o=el('option','',l);o.value=v;o.selected=(draft?.status||c.status)===v;state.append(o)}const notes=el('textarea');notes.value=draft?.notes??c.notes;notes.maxLength=4000;notes.placeholder='Notas de seguimiento…';notes.setAttribute('aria-label','Notas de '+c.name);if(draft)card.dataset.dirty='true';state.className='state '+(draft?.status||c.status);state.disabled=saving;notes.disabled=saving;const setDirty=()=>{if(state.value===c.status&&notes.value===c.notes){drafts.delete(c.id);delete card.dataset.dirty;}else{drafts.set(c.id,{status:state.value,notes:notes.value,version:draft?.version??c.version});card.dataset.dirty='true';}state.className='state '+state.value;updateSaveBar();};state.onchange=setDirty;notes.oninput=setDirty;card.append(state,notes);const stamp=el('p','small',c.marked_at?'Marcado '+new Date(c.marked_at).toLocaleString('es-AR'):'Todavía sin marcación');card.append(stamp);const foot=el('div','foot');foot.append(el('span','',c.sales+' operaciones'));if(/^https?:\/\//i.test(c.url)){const a=el('a','','Ver perfil ↗');a.href=c.url;a.target='_blank';a.rel='noopener noreferrer';foot.append(a)}card.append(foot);grid.append(card)}$('more').hidden=list.length<=limit;updateSaveBar();}
function renderSellers(){const cont=$('sellers');cont.replaceChildren();for(const s of sellers){const row=el('div','sellerrow');const n=clients.filter(c=>c.seller_id===s.id);row.append(el('div','',s.name+' · '+n.length+' clientes · '+n.filter(c=>c.status==='activo').length+' activos'));const b=el('button','','Generar / renovar enlace');b.onclick=()=>{if(!confirm('Se generará un enlace nuevo para '+s.name+'. Cualquier enlace anterior dejará de funcionar. ¿Continuar?'))return;guard(async()=>{const d=await api('link',{seller_id:s.id});$('linkValue').value=location.origin+location.pathname+'#v='+d.token;$('linkDialog').showModal()},b)};row.append(b);cont.append(row)}const old=$('importSeller').value;$('importSeller').replaceChildren();for(const s of sellers){const o=el('option','',s.name);o.value=s.id;$('importSeller').append(o)}if(sellers.some(s=>s.id===old))$('importSeller').value=old;}
$('loginform').onsubmit=e=>{e.preventDefault();key=$('key').value.trim();guard(async()=>{await load();sessionStorage.setItem('ct-key',key);$('key').value='';message('Acceso correcto.')},e.submitter)};
$('logout').onclick=()=>{if(saving)return;if(drafts.size&&!confirm('Hay cambios sin guardar. ¿Salir y descartarlos?'))return;drafts.clear();sessionStorage.removeItem('ct-key');key='';location.hash='';location.reload()};
$('refresh').onclick=()=>{if(saving)return;if(drafts.size&&!confirm('Tenés notas sin guardar. ¿Descartarlas y actualizar?'))return;drafts.clear();guard(load,$('refresh'))};
window.addEventListener('beforeunload',e=>{if(drafts.size){e.preventDefault();e.returnValue=''}});
for(const id of ['search','sort','from','to','duplicates'])$(id).addEventListener('input',()=>{limit=60;render()});
$('clear').onclick=()=>{sellerFilter.clear();statusFilter.clear();for(const id of ['search','from','to'])$(id).value='';$('duplicates').checked=false;renderFilters();render()};$('more').onclick=()=>{limit+=60;render()};$('selectAll').onclick=()=>{filtered().forEach(c=>selected.add(c.id));render()};$('deselect').onclick=()=>{selected.clear();render()};
function exportRows(onlySelected){if(drafts.size)throw Error('Guardá los cambios pendientes antes de exportar.');if(!window.XLSX)throw Error('No se cargó el lector de Excel. Recargá con conexión a Internet.');const list=filtered().filter(c=>!onlySelected||selected.has(c.id));if(!list.length)throw Error('No hay clientes para exportar');const output=list.map(c=>({'Vendedor':sellerName(c.seller_id),'Cliente':c.name,'Red':c.network,'Primera venta':c.first_sale||'','Última venta':c.last_sale||'','Operaciones':c.sales,'Confirmado (USD)':Number(c.paid),'Pendiente (USD)':Number(c.pending),'Estado':labels[c.status],'Notas':c.notes,'Última marcación':c.marked_at||'','Enlace':c.url}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(output),'Clientes');const summary=[{Concepto:'Fecha de exportación',Valor:new Date().toLocaleString('es-AR')},{Concepto:'Vendedores',Valor:sellerFilter.size?[...sellerFilter].map(sellerName).join(', '):'Todos los accesibles'},{Concepto:'Estados',Valor:statusFilter.size?[...statusFilter].map(s=>labels[s]).join(', '):'Todos'},{Concepto:'Última venta desde',Valor:$('from').value},{Concepto:'Última venta hasta',Valor:$('to').value},{Concepto:'Clientes',Valor:list.length},{Concepto:'Confirmado USD',Valor:list.reduce((s,c)=>s+Number(c.paid),0)},{Concepto:'Pendiente USD',Valor:list.reduce((s,c)=>s+Number(c.pending),0)}];XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summary),'Resumen');XLSX.writeFile(wb,'seguimiento_'+new Date().toISOString().slice(0,10)+'.xlsx');message('Excel exportado: '+list.length+' clientes.');}
$('export').onclick=()=>guard(()=>exportRows(false));$('exportSelected').onclick=()=>guard(()=>exportRows(true));
$('newSeller').onsubmit=e=>{e.preventDefault();guard(async()=>{await api('addSeller',{name:$('sellerName').value});$('sellerName').value='';await load();message('Vendedor agregado. Ya podés importar su Excel y generar su enlace.')},e.submitter)};
$('copyLink').onclick=()=>guard(async()=>{await navigator.clipboard.writeText($('linkValue').value);$('copyLink').textContent='Copiado ✓'});$('closeLink').onclick=()=>{$('linkDialog').close();$('linkValue').value='';$('copyLink').textContent='Copiar enlace'};
const fields={name:'Cliente *',paid:'Total pagado / confirmado (USD) *',pending:'Pendiente (USD)',first_sale:'Primera venta',last_sale:'Última venta',sales:'Operaciones',network:'Red social',url:'Enlace'};
function invalidate(){previewRows=null;$('import').disabled=true;$('previewText').textContent='Revisá las columnas y presioná Revisar importación.';}
function mapColumns(auto=true){invalidate();const h=Number($('headerRow').value)-1;if(h<0||h>=rows.length)throw Error('Fila de encabezados inválida');let guessed={};if(auto){try{guessed=TrackerCore.detect(rows.slice(h)).map}catch{}}$('columns').replaceChildren();for(const [k,l]of Object.entries(fields)){const label=el('label','',l),s=el('select');s.id='map_'+k;const no=el('option','','Sin columna');no.value='-1';s.append(no);rows[h].forEach((v,i)=>{const o=el('option','',String(v||'Columna '+(i+1)));o.value=i;s.append(o)});s.value=guessed[k]??-1;s.onchange=invalidate;label.append(s);$('columns').append(label)}}
function chooseSheet(){rows=XLSX.utils.sheet_to_json(book.Sheets[$('sheet').value],{header:1,defval:'',raw:true});try{$('headerRow').value=TrackerCore.detect(rows).header+1}catch{$('headerRow').value=1}mapColumns();}
$('file').onchange=()=>guard(async()=>{invalidate();$('mapping').hidden=true;const f=$('file').files[0];if(!f)return;if(f.size>10*1024*1024)throw Error('El archivo supera 10 MB');if(!window.XLSX)throw Error('No se cargó el lector de Excel. Recargá la página.');book=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});$('sheet').replaceChildren();for(const name of book.SheetNames){const o=el('option','',name);o.value=name;$('sheet').append(o)}chooseSheet();$('mapping').hidden=false;});
$('sheet').onchange=()=>guard(chooseSheet);$('headerRow').onchange=()=>guard(()=>mapColumns());$('importSeller').onchange=invalidate;
$('preview').onclick=()=>guard(()=>{const map={};for(const k of Object.keys(fields))map[k]=Number($('map_'+k).value);previewRows=TrackerCore.parse(rows,Number($('headerRow').value)-1,map);const existing=new Set(clients.filter(c=>c.seller_id===$('importSeller').value).map(c=>c.identity));const updates=previewRows.filter(c=>existing.has(c.identity)).length;$('previewText').textContent=sellerName($('importSeller').value)+': '+previewRows.length+' clientes · '+(previewRows.length-updates)+' nuevos · '+updates+' actualizados · USD '+money(previewRows.reduce((s,c)=>s+c.paid,0))+' confirmado. Estados y notas existentes se conservan.';$('import').disabled=false;});
$('import').onclick=()=>guard(async()=>{if(!previewRows)throw Error('Primero revisá la importación');const d=await api('import',{seller_id:$('importSeller').value,rows:previewRows,filename:$('file').files[0].name});previewRows=null;await load();$('mapping').hidden=true;$('file').value='';message('Importación completa: '+d.count+' clientes. Generá el enlace desde Vendedores y enlaces.')},$('import'));
(async()=>{const fragment=new URLSearchParams(location.hash.slice(1));key=fragment.get('v')||fragment.get('admin')||sessionStorage.getItem('ct-key')||'';if(location.hash)history.replaceState(null,'',location.pathname+location.search);if(key)await guard(async()=>{await load();sessionStorage.setItem('ct-key',key)})})();
