(function(root){
const norm=v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function amount(v){if(v==null||v==='')return 0;if(typeof v==='number'){if(!Number.isFinite(v)||v<0)throw Error('Monto inválido');return v;}let s=String(v).replace(/USD|US\$|\$|\s/gi,'');if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);if(!Number.isFinite(n)||n<0)throw Error('Monto inválido: '+v);return n;}
function date(v){if(v==null||v==='')return null;if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='number')return new Date(Date.UTC(1899,11,30)+Math.round(v)*86400000).toISOString().slice(0,10);let s=String(v).trim(),m=s.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);if(m)s=m[3]+'-'+m[2].padStart(2,'0')+'-'+m[1].padStart(2,'0');if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw Error('Fecha inválida: '+v);return s;}
function identity(name,network,url){let handle=norm(name).replace(/^@/,'');if(url){try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))throw Error();handle=u.hostname.replace(/^www\./,'')+u.pathname.replace(/\/+$/,'').toLowerCase();return handle;}catch{throw Error('Enlace inválido: '+url)}}return norm(network)+':'+handle;}
const aliases={name:['cliente','nombre','usuario','nombre del cliente'],network:['red','red social'],first_sale:['primera venta'],last_sale:['ultima venta'],paid:['confirmado (usd)','total pagado','total pagado (usd)','pagado','confirmado'],pending:['pendiente (usd)','pendiente'],sales:['operaciones','ventas'],url:['enlace','link','perfil']};
function detect(rows){const header=rows.findIndex(r=>r.some(v=>aliases.name.includes(norm(v))));if(header<0)throw Error('No se encontró una columna Cliente, Nombre o Usuario.');const map={};for(const [k,arr] of Object.entries(aliases))map[k]=rows[header].findIndex(v=>arr.includes(norm(v)));return {header,map};}
function parse(rows,header,map){if(map.name<0||map.paid<0)throw Error('Elegí las columnas de cliente y total pagado.');const out=[],seen=new Set();for(let i=header+1;i<rows.length;i++){const r=rows[i];if(r.every(v=>v==null||v===''))continue;try{const get=k=>map[k]>=0?r[map[k]]:null;const name=String(get('name')??'').trim();if(!name)throw Error('Falta nombre');const network=String(get('network')||'Instagram').trim(),url=String(get('url')||'').trim(),id=identity(name,network,url);if(seen.has(id))throw Error('Cliente repetido: '+name+'. Usá una fila consolidada por cliente.');seen.add(id);const first=date(get('first_sale')),last=date(get('last_sale'));if(first&&last&&first>last)throw Error('La primera venta es posterior a la última');const sales=map.sales<0?1:amount(get('sales'));if(!Number.isInteger(sales))throw Error('Operaciones debe ser entero');out.push({identity:id,name,network,url,first_sale:first,last_sale:last,paid:amount(get('paid')),pending:amount(get('pending')),sales});}catch(e){throw Error('Fila '+(i+1)+': '+e.message)}}if(!out.length)throw Error('El archivo no contiene clientes');if(out.length>5000)throw Error('Máximo 5000 clientes por importación');return out;}
root.TrackerCore={norm,amount,date,identity,detect,parse,aliases};if(typeof module!=='undefined')module.exports=root.TrackerCore;
})(globalThis);
